name: health_mate
description: "HealthMate â€“ Personal Health Tracker App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # UI and charts
  fl_chart: ^1.1.1
  provider: ^6.1.2

  # Database and storage
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.2

  # Utilities
  intl: ^0.20.2
  characters: ^1.4.1
  material_color_utilities: ^0.11.1

  # Authentication
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/health.db
