name: health_mate
description: A Flutter HealthMate App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Firebase core
  firebase_core: ^3.7.0

  # Firebase authentication (updated)
  firebase_auth: ^5.7.0

  # Cloud Firestore
  cloud_firestore: ^5.6.12

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Facebook Authentication
  flutter_facebook_auth: ^6.0.1

  # Apple Sign-In
  sign_in_with_apple: ^6.0.0

  # Local storage & database
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.2

  # Charts
  fl_chart: ^0.69.0

  # Date formatting
  intl: ^0.19.0

  # UI Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
